CCMS.Web.Application/Areas/Admin/Models/contract.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Web.Application.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.contract_details_ = new HashSet<contract_details_>();
        }
    
        public string C_c_id_ { get; set; }
        public string C_cg_id_ { get; set; }
        public string C_org_id_ { get; set; }
        public string C_dept_id_ { get; set; }
        public string C_c_state_id_ { get; set; }
        public string C_cont_no_ { get; set; }
        public string C_cont2_no_ { get; set; }
        public string C_fap_no_ { get; set; }
        public string C_title_ { get; set; }
        public string C_descr_ { get; set; }
        public string C_allow_multiple_projects_ { get; set; }
        public string C_allow_multiple_estimate_sets_ { get; set; }
        public string C_allow_multiple_item_sets_ { get; set; }
        public string C_allow_multiple_project_sets_ { get; set; }
        public string C_fund_ { get; set; }
        public string C_orig_value_ { get; set; }
        public string C_orig_days_ { get; set; }
        public string C_cost_method_id_ { get; set; }
        public string C_start_date_ { get; set; }
        public string C_end_date_ { get; set; }
        public string C_closed_date_ { get; set; }
        public string C_create_user_id_ { get; set; }
        public string C_create_timestamp_ { get; set; }
        public string C_mod_user_id_ { get; set; }
        public string C_mod_timestamp_ { get; set; }
        public string C_fap_no2_ { get; set; }
        public string C_fap_no3_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract_details_> contract_details_ { get; set; }
    }
}

CCMS.Web.Application/Areas/Admin/Controllers/ContractController.cs
using CCMS.Web.Application.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net;


namespace CCMS.Web.Application.Areas.Admin.Views.Contract
{
    public class ContractController : Controller
    {
        private const string CONTRACT_VIEWS_PATH = "~/Areas/Admin/Views/Contract/";
        private const string CONTRACT_PARTIAL_VIEWS_PATH = CONTRACT_VIEWS_PATH + "Partials/";
        private const string CONTRACT_NOT_IMPORTED_CONTRACTS_VIEW_PATH = CONTRACT_PARTIAL_VIEWS_PATH + "_NotImportedContracts.cshtml";
        private const string CONTRACT_IMPORT_CONTRACTS_FORM_VIEW_PATH = CONTRACT_PARTIAL_VIEWS_PATH + "_ImportContractsForm.cshtml";

        // GET: Admin/Contract
        public ActionResult Index()
        {
            return View("~/Areas/Admin/Views/Contract/Partials/_ImportContractsForm.cshtml");
        }

        /// <summary>
        /// Action to render import contracts form inside bootstrap popup control
        /// </summary>
        /// <returns>Import contracts form partial view</returns>
        public ActionResult LoadImportContractsForm()
        {
            var viewModel = new ImportContractsVM();
            viewModel.NotImportedContracts = new List<NotImportedContractsVM>();

            return PartialView(CONTRACT_IMPORT_CONTRACTS_FORM_VIEW_PATH, viewModel);
        }

        /// <summary>
        /// Action to retrieve data from PreConstruction using static json/Web API call as source to map required data elements
        /// </summary>
        /// <param name="viewModel">ImportContractsVM page viewmodel</param>
        /// <returns>Filtered contracts results based on the input criteria passed by ImportContractsVM view model</returns>
        [HttpPost]
        public ActionResult GetContracts(ImportContractsVM viewModel)
        {
            viewModel.NotImportedContracts = new List<NotImportedContractsVM>();

            bool isContractNumber = false;
            if (string.IsNullOrEmpty(viewModel.ContractNumber))
            {
                if (!viewModel.StartDate.HasValue)
                {
                    ModelState.AddModelError("StartDate", "From Date is required.");
                }
                if (!viewModel.EndDate.HasValue)
                {
                    ModelState.AddModelError("EndDate", "To Date is required.");
                }
            }
            else
            {
                isContractNumber = true;
                if (!viewModel.StartDate.HasValue || !viewModel.EndDate.HasValue)
                {
                    ModelState.AddModelError("ContractNumber", "Please select either date range or Contract Number.");
                }

            }
            if (true)//(ModelState.IsValid)           
            {
                try
                {
                    List<ProposalVM> proposalInfo = null;

                    //WriteToLog("File Path:  " + Server.MapPath(ConfigurationManager.AppSettings["JsonFilePath"]));

                    //Test and Delete-local-Read Proposal info from json file 
                    var readJsonData = "";
                    using (StreamReader r = new StreamReader(Server.MapPath("~/Content/ApiData/PreConContractDetails.json")))
                    {
                        readJsonData = r.ReadToEnd();
                    }
                    var serializer = new JavaScriptSerializer();
                    serializer.MaxJsonLength = Int32.MaxValue;

                    var json2Model = serializer.Deserialize<List<NotImportedContractsVM>>(readJsonData);
                    var result = serializer.Deserialize<List<ProposalVM>>(readJsonData);
                    //if (result.Count!= 0)
                    //{
                    //    proposalInfo = (new JavaScriptSerializer()).Deserialize<List<ProposalVM>>(result.ToString());//.Deserialize<List<ProposalVM>>(result.Result)
                    //}
                    //End of Reading from JSon file

                    //Web API code -Original
                    ////string contractWebApiUrl = ConfigurationManager.AppSettings["PreConstructionListApi"];

                    ////if (isContractNumber)
                    ////{
                    ////    contractWebApiUrl = string.Format(contractWebApiUrl, viewModel.ContractNumber, string.Empty, string.Empty);
                    ////}
                    ////else
                    ////{
                    ////    contractWebApiUrl = string.Format(contractWebApiUrl, string.Empty, viewModel.StartDate.Value.Date, viewModel.EndDate.Value.Date);
                    ////}

                    ////WriteToLog("GetWebApiUrl " + contractWebApiUrl);
                    ////proposalInfo = GetContractInfoFromPreConstruction(proposalInfo, contractWebApiUrl);
                    /////End of original web API code

                    //Note: Below line is only needed by Jigar
                    CCMSDBEntities db = new CCMSDBEntities();

                    foreach (var data in result)// foreach (var data in proposalInfo)
                    {
                        NotImportedContractsVM notImportedContracts = new NotImportedContractsVM();
                        notImportedContracts.ContractId = data.PROPOSALID;
                        notImportedContracts.ContractNumber = data.PROPOSALNO;
                        notImportedContracts.Description = data.LONGDESCRIPTION;
                        notImportedContracts.Status = data.PROPOSALSTATUS;
                        notImportedContracts.AwardedDate = data.AWARDEDDATE;

                        //Note: below line is changed by Jigar as per his code but no need to change it.
                        //var contract = this._context.Contracts.Get(c => c.ContNo == data.PROPOSALNO).FirstOrDefault();
                        var contract = db.contracts.Where(c => c.C_cont_no_ == data.PROPOSALNO).FirstOrDefault();
                        if (contract != null)
                            notImportedContracts.IsExistingRecord = true;
                        viewModel.NotImportedContracts.Add(notImportedContracts);
                    }

                }
                catch (Exception ex)
                {
                    WriteToLog("Error#: " + ex.InnerException + " Message: " + ex.Message);
                    //Note: below line is commented by Jigar as Not needed for him
                    //LogUtility.LogError("Error importing contracts", ex);
                    ModelState.AddModelError("", ex.InnerException.Message ?? ex.Message);
                    ViewData["EditErrors"] = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToArray();
                }
            }
            //else
            //{
            //    ViewData["EditErrors"] = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToArray();
            //}

            //viewModel.ErrorMessage = String.Join("<br />", ((string[])ViewData["EditErrors"]));

            return PartialView(CONTRACT_NOT_IMPORTED_CONTRACTS_VIEW_PATH, viewModel.NotImportedContracts);
        }

        /// <summary>
        /// Action to perform contract related information insert/update operation into e-MCMS PostgreSQL database using json/Web API call as source to map required data elements
        /// </summary>
        /// <param name="viewModel">NotImportedContractsVM page viewmodel</param>
        /// <returns>Currently Redirects/Refreshes to Admin Contracts datagrid</returns>
        [HttpPost]
        public ActionResult InsertContracts(string contracts)
        {
            //TODO: Complete logic
            var myarray = contracts.Split(',');

            bool contractCompleteImportFailed = false;
            StringBuilder strBuilder = new StringBuilder();
            strBuilder.Append("<ul>");

            List<ProposalVM> proposalInfo = null;

            string contractWebApiUrl = ConfigurationManager.AppSettings["PreConstructionDetailsApi"];

            for (var i = 0; i < myarray.Length; i++)
            {
                contractCompleteImportFailed = false;
                int contractId = 0;
                int? estimateSetId = 0;
                int? projectSetId = 0;
                int? firmId = null;
                int? itemSetId = 0;
                int bidItemId = 0;

                contractWebApiUrl = string.Format(contractWebApiUrl, string.Empty, myarray[i], string.Empty, string.Empty);
                WriteToLog("InsertWebApiUrl: " + contractWebApiUrl);                
                var result = GetContractInfoFromPreConstruction(proposalInfo, contractWebApiUrl).FirstOrDefault();

                DateTime dt = DateTime.Now;

                //Note: Below line is only needed by Jigar
                CCMSDBEntities db = new CCMSDBEntities();

                #region Contract                
                try
                {
                    var contract = db.contracts.Where(r => r.C_cont_no_ == result.PROPOSALNO).FirstOrDefault();

                    if (contract == null)
                    {
                        //contract = new contract();
                        //contract.OrgId = 3;//TODO
                        //contract.DeptId = 43;
                        //contract.CStateId = "N";
                        //contract.ContNo = result.PROPOSALNO;
                        //contract.Cont2No = null;
                        //contract.FapNo = result.FAPNO1;
                        //contract.FapNo2 = result.FAPNO2;
                        //contract.FapNo3 = result.FAPNO3;
                        //contract.Title = result.SHORTDESCRIPTION;
                        //contract.Descr = result.LONGDESCRIPTION;
                        //contract.AllowMultipleProjects = false;
                        //contract.AllowMultipleEstimateSets = false;

CCMS.Web.Application/Areas/Admin/Views/Contract/Partials/_ImportContractsForm.cshtml
@*@using CCMS.Web.Data;
@using CCMS.Web.Application.HtmlHelpers;
@using System.Web.Optimization*@
@model CCMS.Web.Application.Areas.Admin.Models.ImportContractsVM
@{
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <link rel="stylesheet" href="~/Content/toastr.css">
    @Html.DevExpress().GetStyleSheets(
                new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }
            )
    @Html.DevExpress().GetScripts(
                new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new Script { ExtensionSuite = ExtensionSuite.GridView }
            )

</head>

<div class="row">
    <div class="col-md-12">
        <div id="divContractsImportForm col-md-6">
            @using (Html.BeginForm("GetContracts", "Contract", FormMethod.Post, new { id = "frmContractImport", area = "Admin", @class = "form-inline" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                       
                <div class="divHeader">
                    <div class="row">
                        <div class="col-md-12"> Please use the below filters to fetch contract records from Pre Construction</div>
                    </div>
                </div>
                <div class="divBody">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                @*@Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label  col-md-6" })
                                @Html.DevExpress().DateEdit(settings => {
                               settings.Name = "StartDate";
                               settings.Properties.NullText = "MM/dd/yyyy";
                               settings.Properties.EditFormat = EditFormat.Custom;
                               settings.Properties.EditFormatString = "MM/dd/yyyy";
                               //settings.Properties.ClientSideEvents.DateChanged = "StartDateChanged";
                               settings.Width = 100;
                               //settings.Properties.CalendarProperties.FastNavProperties.DisplayMode = FastNavigationDisplayMode.Inline;
                           }).GetHtml()
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })

                            </div>

                            <div class="col-md-4">
                                @*@Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label  col-md-1" })
                                @Html.DevExpress().DateEdit(settings => {
                               settings.Name = "EndDate";
                               settings.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
                               settings.Properties.NullText = "MM/dd/yyyy";
                               settings.Properties.EditFormat = EditFormat.Custom;
                               settings.Properties.EditFormatString = "MM/dd/yyyy";
                               //settings.Properties.ClientSideEvents.DateChanged = "EndDateChanged";
                               settings.Properties.MaxDate = DateTime.Today;
                               settings.Date = DateTime.Today;
                               settings.Width = 100;
                              // settings.Properties.CalendarProperties.FastNavProperties.DisplayMode = FastNavigationDisplayMode.Inline;
                           }).GetHtml()
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6  text-center">
                            -----------(OR)-----------
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                @Html.LabelFor(model => model.ContractNumber, htmlAttributes: new { @class = "control-label col-md-6" })
                                <div class=" col-md-6">
                                    @Html.EditorFor(model => model.ContractNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContractNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="button" id="btnGetContracts" value="Get Contracts" class="btn btn-default" />
                                <input type="button" id="btnResetImportContracts" value="Reset" class="btn btn-default" />
                                <input type="button" value="Close" class="btn btn-default" data-dismiss="modal" aria-label="Close" />
                            </div>
                        </div>
                    </div>
                </div>
            }
            <br />
            <br />
            <div class="row">
                <div id="divNotImportedContracts" class="col-md-12">

                </div>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div id="divImportedContractsStatus" class="col-md-12" style="display:none;">
        <h3>Import Contracts Result</h3>
        <hr />
        <br />
        <div id="divImportedContractsMessage">

        </div>
        <br />
        <br />
        <input type="button" id="btnBack" value="Back" class="btn btn-default" />
        <input type="button" id="btnGotoContracts" value="Go to Contracts" class="btn btn-default" />
    </div>
</div>
<style type="text/css">
    .divHeader {
        color: #201f35;
        background-color: #ebecef;
        border-bottom: 1px solid #cacbd3 !important;
        padding: 5px 10px 0px 10px;
    }

    .divBody {
        border: 1px solid #cacbd3;
        background-color: #f2f3f4;
        overflow: hidden;
        padding: 10px;
    }
</style>

<script type="text/javascript">
    function StartDateChanged() {
        DisableContractNumberControl();
    }

    function EndDateChanged() {
        DisableContractNumberControl();
    }

    function DisableContractNumberControl() {

        if (($.trim($("#StartDate_I").val()).length >= 0) || ($.trim($("#EndDate_I").val()).length >= 0)) {
            $("#ContractNumber_I").attr('disabled', 'disabled');
            $("#ContractNumber_I").val('');
        }
    }

    function GetContracts() {        
        $("#divNotImportedContracts").html('');
        $("#divNotImportedContracts").html('Processing...');
        //Loader-Delete
        //$("#loader").show();

        $("#divImportedContractsMessage").html('');
        $("#divImportedContractsStatus").hide();
        var formData = $("#frmContractImport").serialize();
            var url = '@Url.Action("GetContracts", "Contract", new { area = "Admin"})';
            $.ajax({
                'type': "POST",
                //'data': 'json',
                'url': url,
                data: formData,
                'success': function (content) {                   
                    $("#divNotImportedContracts").html('');
                    $("#divNotImportedContracts").html(content);
                    $("#divNotImportedContracts").show();
                }, error: function (response) {
                    //alert(response.responseText);
                    //alert(r);
                    //alert("Message: " + r.Message);
                    //alert("StackTrace: " + r.StackTrace);
                    //alert("ExceptionType: " + r.ExceptionType);
                    $("#divNotImportedContracts").html(response.responseText);
                }
            });
    }

    $(document).ready(function () {

        $('#btnResetImportContracts').click(function () {
            //$(':input', '#frmContractImport')
            //    .not(':button, :submit, :reset, :hidden, :select')
            //    .val('')
            //    .removeAttr('checked')
            //    .removeAttr('selected')
            //    .removeAttr('disabled');
            $("#StartDate_I").removeAttr('disabled');
            $("#EndDate_I").removeAttr('disabled');
            $("#StartDate_B-1Img").removeAttr('disabled');
            $("#EndDate_B-1Img").removeAttr('disabled');
            $("#ContractNumber_I").removeAttr('disabled');
            $('#frmContractImport').trigger("reset");
            $("#divNotImportedContracts").html('');
            $("#divNotImportedContracts").hide();
            $("#divImportedContractsMessage").html('');
            $("#divImportedContractsStatus").hide();
        });



        $("#StartDate_I").change(function () {
            DisableContractNumberControl();
        });

        $("#EndDate_I").change(function () {
            DisableContractNumberControl();
        });

        $("#ContractNumber_I").change(function () {
            $("#StartDate_I").attr('disabled', 'disabled');
            $("#EndDate_I").attr('disabled', 'disabled');
            $("#StartDate_I").val('');
            $("#EndDate_I").val('');
            $("#StartDate_B-1Img").attr('disabled', 'disabled');
            $("#EndDate_B-1Img").attr('disabled', 'disabled');

            if ($.trim($("#ContractNumber_I").val()).length <= 0) {
                $("#StartDate_I").removeAttr('disabled');
                $("#EndDate_I").removeAttr('disabled');
                $("#StartDate_B-1Img").removeAttr('disabled');
                $("#EndDate_B-1Img").removeAttr('disabled');
            }

        });

        $("#btnGetContracts").click(function (event) {
           
            event.preventDefault();
           
            GetContracts();

        });
        $("#btnBack").click(function (event) {
            event.preventDefault();
            GetContracts();

        });
        $("#btnGotoContracts").click(function (event) {
            event.preventDefault();
            
            var redirectUrl = '@Url.Action("Index", "Contract", new { area = "Admin"})';
            window.location.href = redirectUrl;

        });
    });
</script>